### ISSUE TITLE
Can't use template sensor for ambient/leaf temp offset

### ISSUE THREAD

**Issue by JakeTheRabbit** [vpdchart/vpdchart-card#1]
Hi, 

I have a templated sensor I use to calculate the difference in temperature between the leaf and the ambient temp. Could you make it so that i can put a sensor there instead of manually adding an offset (which is kind of pointless cos its constantly changing) so we could get a much more accurate view of VPD.  I was very excited and I am very thankful for your hard work you've done putting this together. great work. But without the ability to have a live updating temp difference this card is kind of pointless IMO. 

<img width="341" alt="image" src="https://user-images.githubusercontent.com/123831499/216741626-91c7acbc-2fb9-4d85-935a-2268b64feff2.png">

**Comment by bjeanes** [comment]
If you have a leaf temperature measurement sensor which is accurate, then your offset is 0. You don't want to pass both the offset and your accurate leaf temperature. Based on looking over the code, it seems that the offset is added to the leaf temperature sensor to get the "real" leaf temperature. I think that's designed for people who are estimating leaf temperature and passing the air temperature sensor in as the leaf sensor.

Just have `offset: 0` and your two sensors and you _should_ be set up correctly.

**Comment by JakeTheRabbit** [comment]
> If you have a leaf temperature measurement sensor which is accurate, then your offset is 0. You don't want to pass both the offset and your accurate leaf temperature. Based on looking over the code, it seems that the offset is added to the leaf temperature sensor to get the "real" leaf temperature. I think that's designed for people who are estimating leaf temperature and passing the air temperature sensor in as the leaf sensor.
> 
> Just have `offset: 0` and your two sensors and you _should_ be set up correctly.

Awesome thanks I will try again now

**Comment by JakeTheRabbit** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/123831499/222013492-fccfc45f-f26b-4c77-a494-6df436ebb6de.png">

**Comment by JakeTheRabbit** [comment]
Ahhhhhhhhhhh ok I've got it now it has to be '0'

<img width="553" alt="image" src="https://user-images.githubusercontent.com/123831499/222013728-fcf0dae0-743b-455b-81f3-dac221e5d641.png">

**Comment by bogdan42k** [comment]
leaf_temp_offset is now optional in latest release v1.0.1.
